// --- THEME ENGINE ---
// Manages the visual styles: blue, dark, white, red, and green
const themes = ['blue', 'dark', 'white', 'red', 'green'];
let currentIdx = themes.indexOf(localStorage.getItem('user_theme') || 'blue');

function applyTheme(idx) {
    const theme = themes[idx];
    document.documentElement.setAttribute('data-theme', theme);
    localStorage.setItem('user_theme', theme);
}

function cycleTheme() {
    currentIdx = (currentIdx + 1) % themes.length;
    applyTheme(currentIdx);
}
applyTheme(currentIdx);

// --- ADMIN LOCK (SECURE HASHING) ---
let isAdmin = false;

async function adminLogin() {
    const input = prompt("ENTER ACCESS KEY:");
    if (!input) return;

    // .trim() removes accidental spaces from your typing
    const pass = input.trim(); 
    
    // Updated with the specific hash generated by your browser console
    const masterHash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9";
    
    // Convert the user input into a SHA-256 hash
    const msgBuffer = new TextEncoder().encode(pass);
    const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');

    if (hashHex === masterHash) {
        isAdmin = true;
        const zone = document.getElementById('adminZone');
        if (zone) zone.classList.remove('hidden');
        renderLogs();
        alert("Authenticated. Welcome back, Nihadh.");
    } else {
        alert("Access Denied. Incident Logged.");
    }
}

// --- LOG SYSTEM ---
// Stores your activity logs in the browser's local storage
let logs = JSON.parse(localStorage.getItem('nihadh_v4_logs')) || [
    { id: 1, title: "Lab: Steel Mountain", desc: "Privilege escalation via unquoted service paths.", date: "4/13/2026" }
];

function renderLogs() {
    const container = document.getElementById('logsContainer');
    if (!container) return;
    
    container.innerHTML = logs.map(log => `
        <div class="terminal-card p-4 flex justify-between items-center group">
            <div>
                <div class="flex items-center gap-4 mb-1">
                    <span class="text-[10px] font-bold accent-text uppercase tracking-widest">${log.title}</span>
                    <span class="text-[8px] opacity-30">${log.date}</span>
                </div>
                <p class="text-[11px] opacity-60">${log.desc}</p>
            </div>
            ${isAdmin ? `<button onclick="deleteLog(${log.id})" class="text-[9px] text-red-500 font-bold hover:underline">PURGE</button>` : ''}
        </div>
    `).join('');
}

function addLog() {
    if (!isAdmin) return;
    const t = document.getElementById('logTitle'), d = document.getElementById('logDesc');
    if(!t.value || !d.value) return;
    
    logs.unshift({ 
        id: Date.now(), 
        title: t.value, 
        desc: d.value, 
        date: new Date().toLocaleDateString() 
    });
    
    t.value = ''; d.value = '';
    localStorage.setItem('nihadh_v4_logs', JSON.stringify(logs));
    renderLogs();
}

function deleteLog(id) {
    if (!isAdmin) return;
    if(confirm("Confirm deletion of log entry?")) {
        logs = logs.filter(l => l.id !== id);
        localStorage.setItem('nihadh_v4_logs', JSON.stringify(logs));
        renderLogs();
    }
}

// Initialize logs on page load
document.addEventListener('DOMContentLoaded', renderLogs);
